# Generated by Django 6.0.6 on 2026-06-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at', 'title']},
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_available',
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SALE', 'Sale'), ('RENTED', 'Rented')], default='AVAILABLE', max_length=10),
        ),
    ]
