# Generated by Django 6.0.6 on 2026-06-12 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at', 'title']},
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_available',
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('ON_RENT', 'On Rent'), ('ON_SALE', 'On Sale'), ('RENTED', 'Rented'), ('SALE', 'Sale')], default='ON_RENT', max_length=10),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='properties/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
