# Generated by Django 6.0.6 on 2026-06-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_remove_property_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
